### ISSUE TITLE
Not able to fetch data from lxplus

### ISSUE THREAD

**Issue by ltsai323** [IncandelaLab/SharedUI#18]
Got error message "Failed to fetch an update data: 500 - Internal Server Error" from sharedUI.
After object uploaded, the uploaded part is tagged as "(not uploaded to DB)".
But the uploading from SharedUI was confirmed.

Try to use previous version software but the situation keeps the same.

### Reproduce
Activate ShareUI and error message shown but SharedUI is still working.
Everything is good except for the remote part list.
<img width="763" alt="Screenshot 2024-10-22 at 17 06 36" src="https://github.com/user-attachments/assets/238a3e17-7922-4d5a-ae16-6a61abae8b14">

**Comment by danyi211** [comment]
This is due to HGCAL API issues, and George Adamov is in charge of it. I think it's fixed now, but in case of future issues you can submit gitlab tickets here: https://gitlab.cern.ch/hgcal-database/uploads-parts-and-qc-data
