### ISSUE TITLE
Program raised bug when uploading current object

### ISSUE THREAD

**Issue by ltsai323** [IncandelaLab/SharedUI#6]
In master branch, this bug raised on MacOS and Windows WSL+ubuntu.
Step to reproduce bug:

- Create a new baseplate
- Save the baseplate
- Click "Upload current object"
- Bug raised.
![image](https://github.com/IncandelaLab/SharedUI/assets/17274470/66b811f7-ad34-416f-b5ff-7a0df947fe68)

The code seems to failed the if section at line [439 to 454](https://github.com/IncandelaLab/SharedUI/blob/master/mainUI.py#L439-L454).

**Comment by ltsai323** [comment]
The picture shows error twice because I clicked the button twice.

**Comment by danyi211** [comment]
Hi @ltsai323 ,

did you run this command in your terminal as [suggested](https://github.com/IncandelaLab/SharedUI?tab=readme-ov-file#prerequisites) in the README?
```
scp -o ProxyJump=username@lxplus.cern.ch /directory_to_the_xml_file/xxx.xml username@dbloader-hgcal:/home/dbspool/spool/hgc/int2r/
```
The GUI essentially runs this command and will try to look for "Password" in the prompt. Your computer will need to establish a connection with lxplus and dbloader-hgcal hosts at least once, so that the "Password" prompt can be found in the prompt.

**Comment by ltsai323** [comment]
Hi @danyi211,
The command is succeeded in my terminal.
```
scp -o ProxyJump=ltsai@lxplus.cern.ch /Users/ltsai/Downloads/SharedUI-master/filemanager_data/baseplates/6-19-2024/baseplate_test-HGCal-NTU-baseplate_build_upload.xml ltsai@dbloader-hgcal:/home/dbspool/spool/hgc/int2r/ 
```

In this GUI, no password prompt appears after "Upload current object" button clicked. 
The only login prompt showed at the begging, asking for my lxplus account and password.
But in the GUI, no any Password Prompt pops up.
The only prompt shows at the beginning, request my lxplus account and password.

**Comment by danyi211** [comment]
Yes I mean the prompt of this command, not the GUI.
If this succeeded, could you try to upload through GUI again and see if it works?

**Comment by ltsai323** [comment]
Oh it works.

SSH connection requires connection confirmation at first time, this question forbids the scripts.
Thanks.
