### ISSUE TITLE
Program stuck few second when I entered ID creating new baseplate.

### ISSUE THREAD

**Issue by ltsai323** [IncandelaLab/SharedUI#7]
In master branch. This issue is found at both MacOS and Windows WSL.
Program waits for searching result at each keystroke sent.
I thought it is not a bug but it takes half a minute for creating a new component.

Step to reproduce this issue:
- Click "baseplate" tab
- Type something in the ID textbox.
![image](https://github.com/IncandelaLab/SharedUI/assets/17274470/ba5e8722-b4bd-4fa0-a952-21594cbc7bd0)

**Comment by danyi211** [comment]
Yes indeed the GUI will search for every string in the search box.
A workaround is to type the name of the part in a text editor and then copy-paste it into the search box.

**Comment by ltsai323** [comment]
OK, I'll paste ID instead of type ID into the textbook
